### YamlMime:Architecture
metadata:
  title: Multitier Web Application Built for High Availability and Disaster Recovery
  description: Learn how to create a resilient multitier web application built for high availability and disaster recovery on Azure by using VMs.
  author: shubhamsangal-msft
  ms.author: shsangal
  ms.date: 03/31/2026
  ms.topic: example-scenario
  ms.subservice: example-scenario
  ai-usage: ai-assisted
  ms.category:
    - web
    - featured
  ms.custom:
    - product-team
    - bcdr
    - web-apps
    - application-development
    - example-scenario
    - arb-web
name: Multitier web application built for high availability and disaster recovery
azureCategories:
  - web
  - featured
summary: Create a multitier web application built for high availability and disaster recovery on Azure by using Azure virtual machines, availability sets, availability zones, Azure Site Recovery, and Azure Traffic Manager.
products:
  - azure
  - azure-arc
  - sql-server
  - windows
thumbnailUrl: /azure/architecture/browse/thumbs/architecture-disaster-recovery-multi-tier-app.png
content: |
   [!INCLUDE[](multi-tier-app-disaster-recovery-content.md)]
