### YamlMime:Architecture
metadata:
  title: Multi-tier web application built for HA/DR
  description: Learn how to create a resilient multitier web application built for high availability and disaster recovery on Azure.
  author: shubhamsangal-msft
  ms.author: shsangal
  ms.date: 07/09/2024
  ms.topic: example-scenario
  ms.subservice: example-scenario
  ai-usage: ai-assisted
  ms.category:
    - web
    - featured
  ms.custom:
    - product-team
    - bcdr
    - web-apps
    - application-development
    - example-scenario
    - arb-web
name: Multi-tier web application built for HA/DR
azureCategories:
  - web
  - featured
summary: 'Create a multitier web application built for high availability and disaster recovery on Azure using Azure virtual machines, availability sets, availability zones, Azure Site Recovery, and Azure Traffic Manager.'
products:
  - azure
  - azure-arc
  - sql-server
  - windows
thumbnailUrl: /azure/architecture/browse/thumbs/architecture-disaster-recovery-multi-tier-app.png
content: |
   [!include[](multi-tier-app-disaster-recovery-content.md)]
