### YamlMime:Architecture
metadata:
  title: Run reservoir simulation software on Azure
  titleSuffix: Azure Example Scenarios
  description: Run OPM Flow reservoir simulation software and OPM ResInsight visualization software on an Azure HPC compute cluster and visualization VM.
  author: martinekuan
  ms.author: architectures
  ms.date: 07/26/2022
  ms.topic: example-scenario
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.category:
    - compute
  ms.custom:
    - fcp
    - example-scenario
name: Run reservoir simulation software on Azure
azureCategories:
  - compute
summary: Run OPM Flow reservoir simulation software and OPM ResInsight visualization software on an Azure HPC compute cluster and visualization VM.
products:
  - azure-cyclecloud
  - azure-key-vault
  - azure-virtual-machines
thumbnailUrl: /azure/architecture/browse/thumbs/architecture-hpc-reservoir-simulation.png
content: |
   [!include[](reservoir-simulation-content.md)]
