### YamlMime:Architecture
metadata:
  title: WordPress on App Service
  description: Use Azure Front Door, Azure App Service, and other Azure services to deploy a highly scalable and secure installation of WordPress.
  author: claytonsiemens77
  ms.author: pnp
  ms.date: 06/30/2023
  ms.topic: example-scenario
  ms.subservice: example-scenario
  ai-usage: ai-assisted
  ms.category:
    - web
  ms.custom:
    - web-apps
    - scalability
    - example-scenario
    - arb-web
  social_image_url: /azure/architecture/example-scenario/infrastructure/media/wordpress-app-service.png
name: WordPress on App Service
azureCategories:
  - web
summary: Use Azure Front Door, Azure App Service, and other Azure services to deploy a highly scalable and secure installation of WordPress.
products:
  - azure-front-door
  - azure-load-balancer
  - azure-virtual-network
  - azure-app-service
  - azure-database-mysql
thumbnailUrl: /azure/architecture/browse/thumbs/wordpress-app-service.png
content: |
   [!include[](wordpress-app-service-content.md)]
