### YamlMime:Architecture
metadata:
  title: Distributed training, deep learning models
  description: Conduct distributed training of deep learning models across clusters of GPU-enabled VMs by using Azure Machine Learning.
  author: EdPrice-MSFT
  ms.author: architectures
  ms.date: 11/04/2022
  ms.topic: reference-architecture
  ms.service: architecture-center
  ms.subservice: reference-architecture
  ms.category:
    - ai-machine-learning
    - compute
    - media
  ms.custom:
    - azcat-ai
    - ai-machine-learning
name: Distributed training of deep learning models on Azure
azureCategories:
  - ai-machine-learning
  - compute
  - media
summary: Conduct distributed training of deep learning models across clusters of GPU-enabled VMs by using Azure Machine Learning.
products:
  - azure-blob-storage
  - azure-container-registry
  - azure-machine-learning
thumbnailUrl: /azure/architecture/browse/thumbs/distributed-dl-architecture-thumbnail.png
content: |
  [!include[](training-deep-learning-content.md)]
