### YamlMime:Architecture
metadata:
  title: Protect access tokens in a single-page application by using Azure API Management 
  description: Implement a No Token in the Browser architecture for a JavaScript single-page application using API Management.
  author: irarainey
  ms.author: irarainey
  ms.date: 03/10/2023
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: azure-guide
azureCategories:
  - identity
  - security
  - web
products:
  - azure-api-management
  - azure-active-directory
  - azure-app-service-static
name: Protect access tokens in a single-page application by using Azure API Management 
summary: Implement a No Token in the Browser architecture for a JavaScript single-page application by using API Management.
thumbnailUrl: /azure/architecture/browse/thumbs/no-token.png
content: |
  [!include[](secure-single-page-application-authorization-content.md)]