### YamlMime:Architecture
metadata:
  title: Deploy IBM Maximo Application Suite (MAS) on Azure
  description: Learn how to run IBM Maximo Application Suite (MAS) on Azure by using Azure Red Hat OpenShift or self-managed Red Hat OpenShift.
  author: ranieuwe
  ms.author: ronieuwe
  ms.date: 08/06/2026
  ms.update-cycle: 1095-days
  ai-usage: ai-assisted
  ms.topic: example-scenario
  ms.subservice: example-scenario
  ms.custom:
    - linux-related-content
azureCategories:
  - compute
  - containers
  - storage
  - analytics
  - iot
products:
  - azure-files
  - azure-load-balancer
  - azure-redhat-openshift
  - azure-virtual-machines
  - azure-virtual-network
name: Deploy IBM Maximo Application Suite on Azure
summary: Learn how to run IBM Maximo Application Suite (MAS) on Azure by using Azure Red Hat OpenShift or self-managed Red Hat OpenShift.
thumbnailUrl: /azure/architecture/browse/thumbs/deploy-ibm-maximo-application-suite.png
content: |
  [!INCLUDE[](deploy-ibm-maximo-application-suite-content.md)]
