### YamlMime:Architecture
metadata:
  title: Distributed hyperparameter tuning for machine learning models
  description: Use distributed hyperparameter tuning with Azure Machine Learning compute to train scikit-learn and deep learning machine learning models in Python.
  author: fboylu
  ms.author: fboylu
  ms.date: 01/17/2023
  ms.topic: example-scenario
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.custom:
    - azcat-ai
    - ai-machine-learning
    - aml-project-improvement
    - devx-track-python
name: Distributed hyperparameter tuning for machine learning models
azureCategories:
  - ai-machine-learning
  - compute
summary: Use distributed hyperparameter tuning with Azure Machine Learning compute to train scikit-learn and deep learning machine learning models in Python.
products:
  - azure-container-registry
  - azure-cosmos-db
  - azure-data-lake-storage
  - azure-data-science-vm
  - azure-machine-learning
thumbnailUrl: /azure/architecture/browse/thumbs/tune-hyperparameters.png
content: |
  [!include[](training-python-models-content.md)]
