### YamlMime:Architecture
metadata:
  title: Product recommendations for retail using Azure
  titleSuffix: Azure Solution Ideas
  description: Aggregate customer data into complete profiles. Use advanced Azure machine learning models to provide predictive insights on simulated customers.
  author: doodlemania2
  ms.author: pnp
  ms.date: 12/16/2019
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - analytics
  ms.custom:
    - acom-architecture
    - artificial intelligence
    - solution architectures
    - Azure
    - ai gallery
    - interactive-diagram
    - "https://azure.microsoft.com/solutions/architecture/customer-360/"
  social_image_url: /azure/architecture/solution-ideas/articles/media/product-recommendations.png
name: Product recommendations for retail using Azure
azureCategories:
  - analytics
summary: Aggregate customer data into complete profiles. Use advanced Azure machine learning models to provide predictive insights on simulated customers.
products:
  - azure-blob-storage
  - azure-event-hubs
  - azure-hdinsight
  - azure-stream-analytics
  - power-bi
thumbnailUrl: /azure/architecture/browse/thumbs/product-recommendations.png
content: |
   [!include[](product-recommendations-content.md)]
