### YamlMime:Architecture
metadata:
  title: Product recommendations for retail using Azure
  titleSuffix: Azure Architecture Center
  description: Aggregate customer data into complete profiles. Use advanced Azure machine learning models to provide predictive insights on simulated customers.
  author: martinekuan
  ms.author: architectures
  ms.date: 07/27/2022
  ms.topic: solution-idea
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - analytics
  ms.custom:
    - acom-architecture
    - artificial intelligence
    - solution architectures
    - Azure
    - ai gallery
    - interactive-diagram
    - "https://azure.microsoft.com/solutions/architecture/customer-360"
name: Product recommendations for retail using Azure
azureCategories:
  - analytics
summary: Aggregate customer data into complete profiles. Use advanced Azure machine learning models to provide predictive insights on simulated customers.
products:
  - azure-blob-storage
  - azure-event-hubs
  - azure-hdinsight
  - azure-stream-analytics
  - power-bi
thumbnailUrl: /azure/architecture/browse/thumbs/product-recommendations.png
content: |
   [!include[](product-recommendations-content.md)]
