{
 "title": "Manufacturing Ontology dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "Factory location",
    "query": {
     "query": "let ADTInstance = \"FILLINADTURL\"; \nlet ADTQuery = \"SELECT T.equipmentID FROM DIGITALTWINS T WHERE IS_OF_MODEL(T , 'dtmi:digitaltwins:isa95:Area;1')\";\nevaluate azure_digital_twins_query_request(ADTInstance, ADTQuery)\n| extend factory = substring(equipmentID, 10, 15)\n| project factory"
    }
   },
   { "name": "adtURL", "label": "URL of Azure Digital Twins", "query": "FILLINADTURL" }
  ]
 },
 "panels": [
  {
   "title": "Company",
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"font-style: italic; text-align: center;\" markdown=\"1\">\r\n\r\n# Contoso Factory\r\n\r\n</div>"
   },
   "targets": [
    {
     "database": "expmanufont-DB",
     "expression": {
      "from": { "property": { "name": "AdtPropertyEvents", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let ADTInstance = \"${adtURL}\"; \nlet ADTQuery = \"SELECT T.equipmentID FROM DIGITALTWINS T WHERE IS_OF_MODEL(T , 'dtmi:digitaltwins:isa95:Area;1')\";\nevaluate azure_digital_twins_query_request(ADTInstance, ADTQuery)\n| extend factory = substring(equipmentID, 10, 15)\n| project factory",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Number of plants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "expmanufont-DB",
     "expression": {
      "from": { "property": { "name": "AdtPropertyEvents", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let ADTInstance = \"${adtURL}\"; \nlet ADTQuery = \"SELECT T FROM DIGITALTWINS T WHERE IS_OF_MODEL(T , 'dtmi:digitaltwins:isa95:Area;1')\";\nevaluate azure_digital_twins_query_request(ADTInstance, ADTQuery)\n| count\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Number of machines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "expmanufont-DB",
     "expression": {
      "from": { "property": { "name": "AdtPropertyEvents", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let ADTInstance = \"${adtURL}\"; \nlet ADTQuery = \"SELECT T FROM DIGITALTWINS T WHERE IS_OF_MODEL(T , 'dtmi:digitaltwins:opcua:nodeset;1')\";\nevaluate azure_digital_twins_query_request(ADTInstance, ADTQuery)\n| count\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "OEE",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "expmanufont-DB",
     "expression": {
      "from": { "property": { "name": "AdtPropertyEvents", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let oee = CalculateOEEForLine(\"${location}\", 6,6);\nprint round(oee * 100, 2)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "OEE stations",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "expmanufont-DB",
     "expression": {
      "from": { "property": { "name": "AdtPropertyEvents", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "print round(CalculateOEEForLine(\"${location}\", 6, 6) * 100, 2)\n\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Discarded products",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "expmanufont-DB",
     "expression": {
      "columns": {
       "columns": [
        "TimeStamp",
        "Id",
        "Value",
        "Key"
       ],
       "type": "property"
      },
      "from": { "property": { "name": "AdtPropertyEvents", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "OPCUANodeValue" }, "property": { "name": "Key", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "query": "let horizon = ($__timeTo - $__timeFrom) / 2;\nlet dt = 5m;\nlet intermediateTable = AdtPropertyEvents\n| where $__timeFilter(TimeStamp)\n| where Id == toscalar(GetDigitalTwinIdForUANode(\"assembly\", \"${location}\", \"NumberOfDiscardedProducts\"));\nintermediateTable\n| where isnotnull(SourceTimeStamp)\n| join intermediateTable on $left.TimeStamp == $right.TimeStamp\n| where Key1 == \"OPCUADisplayName\"\n| order by TimeStamp asc \n| make-series actual=avg(toint(Value)) on TimeStamp from $__timeFrom to $__timeTo + horizon step dt\n| extend forecast = series_decompose_forecast(actual, toint(horizon/dt))\n| project-rename Timestamp=TimeStamp",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Manufactured products",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "database": "expmanufont-DB",
     "expression": {
      "columns": {
       "columns": [
        "TimeStamp",
        "Id",
        "Value",
        "Key"
       ],
       "type": "property"
      },
      "from": { "property": { "name": "AdtPropertyEvents", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "OPCUANodeValue" }, "property": { "name": "Key", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "query": "let horizon = ($__timeTo - $__timeFrom) / 2;\nlet dt = 5m;\nlet intermediateTable = AdtPropertyEvents\n| where $__timeFilter(TimeStamp)\n| where Id == toscalar(GetDigitalTwinIdForUANode(\"assembly\", \"${location}\", \"NumberOfManufacturedProducts\"));\nintermediateTable\n| where isnotnull(SourceTimeStamp)\n| join intermediateTable on $left.TimeStamp == $right.TimeStamp\n| where Key1 == \"OPCUADisplayName\"\n| order by TimeStamp asc \n| make-series actual=avg(toint(Value)) on TimeStamp from $__timeFrom to $__timeTo + horizon step dt\n| extend forecast = series_decompose_forecast(actual, toint(horizon/dt))\n| project-rename Timestamp=TimeStamp",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Assembly ${Location} Energy Consumption",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 }
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "database": "expmanufont-DB",
     "expression": {
      "from": { "property": { "name": "AdtPropertyEvents", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let intermediateTable = AdtPropertyEvents\n| where $__timeFilter(TimeStamp)\n| where Id == toscalar(GetDigitalTwinIdForUANode(\"assembly\", \"${location}\", \"pressure\"));\nintermediateTable\n| where isnotnull(SourceTimeStamp)\n| join intermediateTable on $left.TimeStamp == $right.TimeStamp\n| where Key1 == \"OPCUADisplayName\"\n| order by TimeStamp desc\n| make-series num=avg(todouble(Value)) on TimeStamp from $__timeFrom to $__timeTo step 1s\n| extend (anomalies, score, baseline) = series_decompose_anomalies(num, 0.5, -1, 'linefit')\n| project-rename Timestamp=TimeStamp\n// | project Timestamp, anomalies, num, baseline",
     "querySource": "raw"
    }
   ]
  }
 ]
}