### YamlMime:Architecture
metadata:
  title: Training and procedural guidance powered by mixed reality
  titleSuffix: Azure Solution Ideas
  description: Help employees learn processes and materials effectively by providing persistent holographic instructions mapped to precise locations in physical workspaces.
  author: martinekuan
  ms.author: architectures
  ms.date: 06/14/2022
  ms.topic: solution-idea
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - mixed-reality
  ms.custom:
    - acom-architecture
    - ai-ml
    - Azure Spatial Anchors
    - Azure Active Directory
    - Cosmos DB
    - Azure App Service
    - Media Services
    - Microsoft HoloLens
    - Video Indexer
    - interactive-diagram
    - "https://azure.microsoft.com/solutions/architecture/training-and-procedural-guidance-powered-by-mixed-reality"
name: Training and procedural guidance powered by mixed reality
azureCategories:
  - mixed-reality
summary: Help employees learn processes and materials effectively by providing persistent holographic instructions mapped to precise locations in physical workspaces.
products:
  - azure-media-services
  - azure-spatial-anchors
  - azure-video-indexer
thumbnailUrl: /azure/architecture/browse/thumbs/training-and-procedural-guidance-powered-by-mixed-reality.png
content: |
   [!include[](training-and-procedural-guidance-powered-by-mixed-reality-content.md)]
